plugins {
    id 'java'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.3.3'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.service'
version = '1.2' // version 갱신 후에, publish task 수행, s3에 신규 프로젝트 업로드

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation group: 'com.squareup.okhttp3', name: 'okhttp', version: '4.12.0'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.17.2'
    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.11.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

publishing {
    publications {
        library(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "s3://${project.findProperty('AWS_S3_BUCKET_NAME')}/maven"
            credentials(AwsCredentials) {
                accessKey project.findProperty('AWS_S3_BUCKET_ACCESS_KEY_ID')
                secretKey project.findProperty('AWS_S3_BUCKET_SECRET_ACCESS_KEY_ID')
            }
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
